new shapes
rmfranken/rdf_tools pull request #1
Opened 2023-04-05 10:02 UTC by vancauwe

new shapes include the following information:
- ORCID ID
- Working Percentage
- Past Employers
- WorksDays (Monday, Tuesday, etc)

2023-04-12 08:37 UTC, supermaxiste requested changes
Excellent job @vancauwe! I could potentially extend this PR since at the last linked data training I found some nice ontologies for soft skills and job domain, but I need to see if I find time for it

2023-04-12 08:37 UTC, supermaxiste commented on Projects/SDSC_Internal_KG/SDSC_IKG_shapes_new.ttl
> +@prefix rdf4j: <http://rdf4j.org/schema/rdf4j#> .
Duplicate

2023-04-12 08:37 UTC, supermaxiste commented on Projects/SDSC_Internal_KG/SDSC_IKG_shapes_new.ttl
> +@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
Duplicated line

2023-04-12 08:37 UTC, supermaxiste commented on Projects/SDSC_Internal_KG/SDSC_IKG_shapes_new.ttl
> +  sh:path qudt:unit ;
Here `qudt` needs to be defined as a prefix `<http://qudt.org/schema/qudt#>`

2023-04-12 08:37 UTC, supermaxiste commented on Projects/SDSC_Internal_KG/SDSC_IKG_shapes_new.ttl
> +  sh:description "The ORCID iD is an https URI with a 16-digit number that is compatible with the ISO Standard (ISO 27729), also known as the International Standard Name Identifier (ISNI)."^^rdf:HTML
Lil lowercase in ORCID ID

2023-04-20 11:22 UTC, rmfranken requested changes
get 2 wurk

2023-04-20 14:26 UTC, rmfranken commented on Projects/SDSC_Internal_KG/SDSC_IKG_shapes_new.ttl
> +    sh:pattern "https://orcid.org/\d{4}-\d{4}-\d{4}-\d{4}" ;
@vancauwe oh btw, the regex will require extra escapes: "https://orcid.org/\\d{4}-\\d{4}-\\d{4}-\\d{4}" , since backslash is a escape character in rdf AND in regex, so you need one to escape the regex, and one to escape the rdf/turtle.

2023-05-11 06:53 UTC, supermaxiste commented on Projects/SDSC_Internal_KG/test_shapes/SDSC_IKG_shapes_new_test.ttl
> +@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
`rdf` is duplicated

2023-05-11 06:53 UTC, supermaxiste commented on Projects/SDSC_Internal_KG/test_shapes/SDSC_IKG_shapes_new_test.ttl
> +@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
`rdfs` is duplicated

2023-05-11 06:54 UTC, supermaxiste commented on Projects/SDSC_Internal_KG/test_shapes/SDSC_IKG_shapes_new_test.ttl
> +@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
`xsd` is duplicated from line 9

2023-05-11 06:55 UTC, supermaxiste commented on Projects/SDSC_Internal_KG/test_shapes/SDSC_IKG_shapes_new_test.ttl
> +@prefix owl: <http://www.w3.org/2002/07/owl#> .
`owl` is duplicated from line 11

2023-05-11 06:55 UTC, supermaxiste commented on Projects/SDSC_Internal_KG/test_shapes/SDSC_IKG_shapes_new_test.ttl
> +@prefix sesame: <http://www.openrdf.org/schema/sesame#> .
`sesame` duplicated from line 21

2023-05-11 06:57 UTC, supermaxiste commented on Projects/SDSC_Internal_KG/test_shapes/SDSC_IKG_shapes_new_test.ttl
> +  schema:WorkExperience-jobEndDate "01-09-2012"^^xsd:date;;
There's a double `;;` not sure if this can cause an extra error

2023-05-11 07:01 UTC, supermaxiste reviewed
Found some duplicate prefixes and a little mistake with punctuation, great job for all the rest 👍

2023-05-16 05:19 UTC, rmfranken requested changes
Let's chat about these (or the comments if they don't make sense), I think you're very well on the right track, and I think we can iron out all these shapes in half an hour.

2023-05-16 05:19 UTC, rmfranken commented on Projects/SDSC_Internal_KG/test_shapes/SDSC_IKG_shapes_new_test.ttl
> +  schema:WorkExperience-workPercentage 80;
Also I just realized that workPercentage is not an actual schema.org property, and that you did make a shape following the above modelling technique. In this case, I would 
1. revert to making the shape a simple one again (so modelling the shape to conform this instance data)
2. change the namespace (maybe use ":" ) of the property and propertyshape (since they don't exist in schema.org), same goes for WorkExperience and orcidID schema.org does not have such a class nor a property. For orcidId you could use the md4i ontology (https://nfdi4ing.pages.rwth-aachen.de/metadata4ing/metadata4ing/index.html) which has already defined a property for it.

2023-05-16 05:19 UTC, rmfranken commented on Projects/SDSC_Internal_KG/SDSC_IKG_shapes_new.ttl
I don't fully understand why, but I can't seem to add inline comments anymore to this file 😕 The namespace schema.org should also be removed here for the properties that don't actually resolve to schema.org (and thinking about it changing the nodeshape namespaces also makes sense, as there are no shapes officially published on schema.org)

furthermore, I noticed 
`sh:property (
    sh:path schema:url ;
    sh:pattern "https://orcid.org/\d{4}-\d{4}-\d{4}-\d{4}" ;
    ) ;
.`

Which is almost correct.  I think you meant to use sh:nodeKind sh:IRI, instead of the sh:path schema:url. The latter would indicate that you expect the property schema:url to be filled in (which you don't, because you want orcidId filled in), the former indicates that the VALUE for the property should be an IRI. So the sh:path should change to whatever property we are using for orcidId probably the one from Metdata4ING, and the sh:nodeKind statement should be added)

2023-05-30 06:40 UTC, merged